### ISSUE TITLE
Set modified after substitute (cr) 

### ISSUE THREAD

**Issue by Konfekt** [osyo-manga/vim-over#35]
After substitute, changes are not saved when the buffer is saved by :update. 

To solve this, set modified afterwards.

**Comment by justinmk** [comment]
I also noticed that the buffer appears unmodified after `OverCommandLine %s/foo/bar/g`. I had not realized until now that the changes *are not saved* to disk.

**Comment by Konfekt** [comment]
Yeah, but there is
```vim
		    if b:changedtick
		      seltocal modified
                   endif
```
to the rescue. To be issued after `<CR>` is hit in `OverCommandLine`.

**Comment by osyo-manga** [comment]
Thanks issues.
I fixed it 9b8f1aba12444433f6473085213c8eec704be98f
Please update plugin.

**Comment by Konfekt** [comment]
Yep, thanks, it's fixed.

**Comment by osyo-manga** [comment]
OK :)
