### ISSUE TITLE
Clear highlight

### ISSUE THREAD

**Issue by max** [osyo-manga/vim-over#36]
Is it possible to clear the highlight if you want to abort a search and replace?

**Comment by justinmk** [comment]
`:h :nohlsearch`

**Comment by max** [comment]
Thanks for the quick reply. I tried that before opening the issue. Here's a screencast:

![screencap](https://cloud.githubusercontent.com/assets/111631/6609407/34cc6780-c80e-11e4-8929-aa6aae1b8f46.gif)

P.S: I'm aborting the `OverCommandLine` mode with <C-c>. Maybe that's the issue?

**Comment by osyo-manga** [comment]
Thanks for issues :)
It is bug :(
I fixed it.
Please update plugin.

**Comment by max** [comment]
Woot! That did it:

![screencap-1](https://cloud.githubusercontent.com/assets/111631/6609519/b9f58f44-c80f-11e4-9448-bffb3eabbcdd.gif)

When I try to do the same on an unsaved file (new buffer) I get:

![screencap](https://cloud.githubusercontent.com/assets/111631/6609522/c513e786-c80f-11e4-850c-64d011511d9f.gif)

**Comment by osyo-manga** [comment]
OK, Thanks :)
