### ISSUE TITLE
OverCommandLineに入力でE803

### ISSUE THREAD

**Issue by aiya000** [osyo-manga/vim-over#37]
特定条件下でOverCommandLineになんらかの入力を与えることで以下の例外が発生します。
```
function <SNR>302_finish..<SNR>302_reset_match の処理中にエラーが検出されました:
行    3:
E803: ID not found: 60
function over#command_line..over#command_line#start の処理中にエラーが検出されました:
行    3:
E171: :endif がありません
```
発生箇所はこちらです。

autoload/over/command_line/substitute.vim: s:reset_match()

- - -
環境は以下です。
Windows7 64bit
Kaoriya Vim 7.4.648
- - -

再現条件は不明ですが、
OverCommandLineでEscや<C-c>を押下した以後？
必ず発生するようになります。
( Vim起動直後には発生しません )

**Comment by aiya000** [comment]
失礼しました。
再現条件は不明、
再現タイミングはOverCommandLineで異常入力をした？ 以後ずっと、
OverCommandLineに入力を1文字与えた段階で発生するようになる…という感じです。

**Comment by osyo-manga** [comment]
ありがとうございます。こちらでも見てみます。

**Comment by osyo-manga** [comment]
すみません、この問題なのですが最新版で再現したのでしょうか（直前に直した記憶がある。

**Comment by aiya000** [comment]
はい、9ef228655f4dab2d83c0b9af10d59c5b1a7aad7dにて再現した記憶があります。
あ…ただ、以前と比べると、いつの間にか例外が発生しなくなったりも…するようになってるようです。
すみません、もう少し見てみます。

**Comment by aiya000** [comment]
最新コミットで再現することを確認しました。

**Comment by osyo-manga** [comment]
うーん、再現する直前のコマンドや操作とかってわかりますか？
実際のところ、対応するのは簡単なんですが、原因不明なのがちょっと気になるので。

**Comment by aiya000** [comment]
すみませんわかりません…。
:bdeleteや:b fooなどのバッファ系が怪しいかな…？ とは思っているのですが…全く確証がありません。

関係があるかはわかりませんが、ごく稀にmatchitの%が効かなくなることがあります。
(関係があるかは全くわかりません…)

**Comment by osyo-manga** [comment]
とりあえず、対応はしてみました。
これでエラーは出なくなると思います。
ただ、根本的な解決ではないので不具合等（ハイライトが残ったままになるとか）があれば教えてもらえると助かります。

**Comment by aiya000** [comment]
ありがとうございますっ！！
もう一つ、`os`hoge`om`foo… (でしたっけ？)
という``に囲まれた区切り文字がバッファに残りつつsyntax highlight (conceal？) によって隠れていたりするものは確認していますが…こちらも原因の検討がつきません…。

ハイライトが残ることもやはりあるので、原因らしき操作の検討がついたらまた報告させてくださいっ！

**Comment by osyo-manga** [comment]
> という``に囲まれた区切り文字がバッファに残りつつsyntax highlight (conceal？) によって隠れていたりするものは確認していますが…こちらも原因の検討がつきません…。

これもバグですね。
ただ、再現手順がわからないとちょっと対処が難しそうです。
多分、 `OverCommandLine` 上で特定のコマンドを入力実行した時に再現するとは思うのですが。

**Comment by osyo-manga** [comment]
`s:reset_match()` もそうですが、この問題は終了処理が正しく行われていないのが原因なので、再現する直前の操作内容（実行したコマンド等）が影響してきます。
なので、再現した直前に `OverCommandLine` で行った事が重要になってきます。

**Comment by aiya000** [comment]
とりあえず以下が.vimrcに書いた、問題になりそうなものです。
```
nnoremap <silent>       :%s/       :<C-u>OverCommandLine<CR>%s/
nnoremap <silent><expr> <C-k><C-s> ':OverCommandLine<CR>%s/\<' . expand('<cword>') . '\>/'
vnoremap <silent>       :s/        :<C-u>OverCommandLine<CR>'<,'>s/
```
これの<C-k><C-s>などで、over.vimのコマンドラインの描画中に<C-c>などを押す時があるので、
それが関係しているかも…。
( ただし意図的にその操作を行っても再現せず )

**Comment by osyo-manga** [comment]
んーそれだけみると問題なさそうには見えますがわからんですなぁ…。

**Comment by aiya000** [comment]
こちらは頻度が低いので (今回のように例外出ないし)、また何かわかれば報告しますー！

**Comment by osyo-manga** [comment]
あ、あと

```vim
nnoremap <silent><expr> <C-k><C-s> ':OverCommandLine<CR>%s/\<' . expand('<cword>') . '\>/'
```

よりも

```vim
nnoremap <silent><expr> <C-k><C-s> ':OverCommandLine %s/\<' . expand('<cword>') . '\>/<CR>'
```

のように `:OverCommandLine` にプロンプトに入力される文字列を直接渡したほうが動作が早くなります。

**Comment by aiya000** [comment]
なんと引数を渡せたとは！？
よく見てなかった…ありがたや…。

**Comment by aiya000** [comment]
問題が発覚し次第、またissueを開く形の方がよろしいでしょうか？
( こちらのissueは閉じた方がいいでしょうか )

**Comment by osyo-manga** [comment]
んーしばらく様子見て問題がなければ閉じる方針でいいと思います。
（現状問題ないと感じればもう閉じちゃておっけーです。

**Comment by aiya000** [comment]
こちらは全く問題なさそうなので閉じますー！
ありがとうござましたーっ！
![zzm_kiritan_utsu](https://cloud.githubusercontent.com/assets/4897842/6917584/ddd8a47e-d7e0-11e4-9dae-0497e3bf524d.png)

**Comment by aiya000** [comment]
でかい。
