### ISSUE TITLE
%s/foo/foo/で文字列が置き換わり切らない

### ISSUE THREAD

**Issue by aiya000** [osyo-manga/vim-over#38]
問題
元文字列 == 置き換え後文字列
であると以下の問題が起きます。
```
exam) %s/foo/foo/g
```
また、ignorecaseである場合は上記の比較にignorecaseが適用されます。
なのでignorecaseの場合のみ以下でも問題が起きます。
```
exam) %s/foo/Foo/g
```

実行操作
```
nnoremap <silent><expr> <C-k><C-s> ':OverCommandLine %s/\<' . expand('<cword>') . '\>/<CR>'
```
( の```<C-k><C-s>``` )

(OverCommandLine)
```
> %s/\<ExecApplyOrder\>/execApplyOrder/g
```
ここで```<CR>```すると

対象文字列が
```
`os`execApplyOrder`om`execApplyOrder`oe`
```

となります。
( 実際はconcealとsyntax highlightされ
```
execApplyOrderexecApplyOrder
```
と表示されます)

**Comment by osyo-manga** [comment]
すみません、何が問題なのかよくわかかりませんでした…。

> `> %s/\<ExecApplyOrder\>/execApplyOrder/g`

これですが手元では再現しませんでした。
再現する最小の vimrc を教えていただけないでしょうか。

**Comment by osyo-manga** [comment]
あとできれば具体的な再現手順も教えてもらえると助かります。

**Comment by aiya000** [comment]
最小vimrcは以下のみです。 (以下のディレクトリにvim-overが存在します)
```
set rtp+=~/.vim/bundle/vim-over
```

再現手順ですが、これで再現します。
```
$ vim -u (上記のみを記述したvimrc)
(insert modeでaaaaと入力)
:OverCommandLine<CR>
> s/aaaa/aaaa/
````

すみません、環境を記述していませんでした。
以下の2環境で確認しています。
Windows7 64bit kaoriya GVim 7.4.648
Ubuntu 14.10 64bit Vim 7.4.560

**Comment by osyo-manga** [comment]
ありがとうございます。
あと『%s/foo/foo/で文字列が置き換わり切らない』とありますが、期待する挙動はどんなものなのでしょうか。

**Comment by aiya000** [comment]
すみません、そこらへん適切でなかったですね…。

期待する動作はignorecase上での
```> %s/foo/Foo/g```
が動作することです。

**Comment by osyo-manga** [comment]
> 期待する動作はignorecase上での

この『ignorecase上での』というのはどういうことでしょうか。

**Comment by aiya000** [comment]
:set ignorecase
を行っていた場合、
OverCommandLineで
```> s/foo/foo/g```
だけでなく
```> s/foo/Foo/g```
でも問題が起きます。

こちらの```> s/foo/Foo/g```
を行った場合、テキストにこのような変更が起きて欲しいです。

before
```
foo
```

after
```
Foo
```

actual
```
`os`Foo`om`Foo`oe`
```

**Comment by osyo-manga** [comment]
ちょっと複数の問題が出ているようなので切り分けないのですが、まず `ignorecase` の問題からお願いできますか。
手元で `ignorecase` の設定を変えて試してみましたが問題なく動作しました。

**Comment by aiya000** [comment]
はい。
この設定では以下の2つの問題が発生します。

tmp_vimrc
```
set ignorecase
set rtp+=~/.vim/bundle/vim-over
```

実行操作
```
$ vim -u tmp_vimrc foo.txt
(foo.txtに文字列'foo'を入力)
:OverCommandLine
> s/foo/Foo/
```

foo.txtの結果内容
```
`os`Foo`om`Foo`oe`
```

です。

**Comment by osyo-manga** [comment]
そちらで起こっている問題は以下のようなものでしょうか

## vimrc

```vim
" test_vimrc
set rtp+=~/.vim/bundle/vim-over
```

## 再現手順

1. `$ vim -u test_vimrc`
2. 『foo』と入力
3. `:OverCommandLine s/foo/hoge/` を実行
4. `foo` を `hoge` と置換して欲しいが置換されない

**Comment by aiya000** [comment]
いえ、わかりにくくてすみません…。

```foo```は```hoge```に置き換わります。
ただし
```foo```は```Foo```に置き換わりません。

**Comment by osyo-manga** [comment]
> この設定では以下の2つの問題が発生します。

手元で試してみましたが問題なく動作（`Foo` が `foo` と置換）されました。
書き忘れてましたが手元の環境は以下になります。

* Ubuntu 14.10
* Vim 7.4.682

**Comment by aiya000** [comment]
すみません、
こちらは
```
" test_vimrc
set ignorecase
set rtp+=~/.vim/bundle/vim-over
```
である場合です。

再現しませんか…。
最新コミットはf690626ですよね…。

**Comment by osyo-manga** [comment]
全く関係ない場所ですがちょっと push 漏れがあったのでもう1度更新してもらえないでしょうか
d0f37a159d4c13c2c16bddb9aee176d0f3a6b869 です。

**Comment by osyo-manga** [comment]
ちなみに他の方にも試してもらったのですが、そちらでも問題なく動作しているようです。

**Comment by aiya000** [comment]
あれー、更新しましたが再発しますね…。
うーん、ハイゼンバグゥ…。

**Comment by osyo-manga** [comment]
うーん、対応はしたいのですがこちらで再現しないので難しそうですねぇ。
もう1度確認しますが、

## vimrc

```vim
" test_vimrc
set rtp+=~/.vim/bundle/vim-over
```

## 再現手順

1. `$ vim -u test_vimrc`
2. 『foo』と入力
3. `:OverCommandLine s/foo/Foo/` を実行
4. `foo` を `Foo` と置換して欲しいが置換されない

という手順であっていますか？
何か抜けていたり足りない動作はありませんか？

**Comment by aiya000** [comment]
実行コマンドが```:OverCommandLine s/foo/Foo/```である場合はvimrcに以下の項目が足りません。
```
set ignorecase
```

何度も申し訳ないです、正しくは以下です。
- - -
##vimrc
- - -
```
" test_vimrc
set ignorecase
set rtp+=~/.vim/bundle/vim-over
```
## 再現手順
- - -
1. ```$ vim -u test_vimrc```
2. 『foo』と入力
3. ```:OverCommandLine s/foo/Foo/``` を実行
4. ```foo```を```Foo```を置換して欲しいが置換されない

**Comment by osyo-manga** [comment]
> 実行コマンドが:OverCommandLine s/foo/Foo/である場合はvimrcに以下の項目が足りません。

あーすみません、手元だと追加してたんですが、issues に投げたのだと思いっきり抜けたました…。
改めて提示してもらった手順で試してみたのですがやっぱりこちらでは再現しませんでした。
うーん、あと違うのはバージョンぐらいですかねぇ…。
ちょっと他の方にも試してもらおうと思います。

**Comment by osyo-manga** [comment]
あ、あと一応確認なのですが `:OverCommandLine` 経由ではなくて直接 `:s/foo/Foo/` を実行するとどうでしょうか。

**Comment by 0xBADDCAFE** [comment]
@aiya000 指定の動作を試してみましたが、これは再現していないということで間違いないでしょうか。

![over](https://cloud.githubusercontent.com/assets/599164/6992830/e3a18fe6-db1a-11e4-8231-ce1e38cce19a.gif)

**Comment by aiya000** [comment]
- - -
:OverCommandLine 経由ではなくて直接 :s/foo/Foo/ を実行するとどうでしょうか。
- - -
test_vimrcにて試してみたところ、問題なく```foo```が```Foo```に置き換わりました。
oh...

@0xBADDCAFE
oh..!!
はい、間違いなく再現していません。

ちょっとこちらでもgifを取れるようにしてみます。

**Comment by aiya000** [comment]
こんな感じですー。
![over_vim_issue](https://cloud.githubusercontent.com/assets/4897842/6993912/5f4040a0-db40-11e4-8ada-258bb2211c27.gif)

**Comment by osyo-manga** [comment]
ありがとうございます。
やっと何が起きているのかが理解出来ました。
ただ、どちらにしても再現はしないんですよねぇ。

**Comment by osyo-manga** [comment]
申し訳ないのですが、`:version` の出力結果をすべて教えていただけないでしょうか。

**Comment by aiya000** [comment]
はい、これです。

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  1 2015 22:08:29)
適用済パッチ: 1-560
Compiled by aiya000@bluemc-H116K
Huge 版 with GTK2-GNOME GUI.  機能の一覧 有効(+)/無効(-)
+acl             +conceal         +farsi           +libcall         +mouse_netterm   +profile         +syntax          +visualextra
+arabic          +cryptv          +file_in_path    +linebreak       +mouse_sgr       +python          +tag_binary      +viminfo
+autocmd         +cscope          +find_in_path    +lispindent      -mouse_sysmouse  -python3         +tag_old_static  +vreplace
+balloon_eval    +cursorbind      +float           +listcmds        +mouse_urxvt     +quickfix        -tag_any_white   +wildignore
+browse          +cursorshape     +folding         +localmap        +mouse_xterm     +reltime         -tcl             +wildmenu
++builtin_terms  +dialog_con_gui  -footer          +lua             +multi_byte      +rightleft       +terminfo        +windows
+byte_offset     +diff            +fork()          +menu            +multi_lang      +ruby            +termresponse    +writebackup
+cindent         +digraphs        +gettext         +mksession       -mzscheme        +scrollbind      +textobjects     +X11
+clientserver    +dnd             -hangul_input    +modify_fname    +netbeans_intg   +signs           +title           -xfontset
+clipboard       -ebcdic          +iconv           +mouse           +path_extra      +smartindent     +toolbar         +xim
+cmdline_compl   +emacs_tags      +insert_expand   +mouseshape      +perl            -sniff           +user_commands   +xsmp_interact
+cmdline_hist    +eval            +jumplist        +mouse_dec       +persistent_undo +startuptime     +vertsplit       +xterm_clipboard
+cmdline_info    +ex_extra        +keymap          +mouse_gpm       +postscript      +statusline      +virtualedit     -xterm_save
+comments        +extra_search    +langmap         -mouse_jsbterm   +printer         -sun_workshop    +visual          +xpm
      システム vimrc: "$VIM/vimrc"
        ユーザ vimrc: "$HOME/.vimrc"
     第2ユーザ vimrc: "~/.vim/vimrc"
         ユーザ exrc: "$HOME/.exrc"
     システム gvimrc: "$VIM/gvimrc"
       ユーザ gvimrc: "$HOME/.gvimrc"
    第2ユーザ gvimrc: "~/.vim/gvimrc"
    システムメニュー: "$VIMRUNTIME/menu.vim"
       省略時の $VIM: "/usr/local/share/vim"
コンパイル: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2  -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgnomeui-2.0 -I/usr/include/gnome-keyring-1 -I/usr/include/libbonoboui-2.0 -I/usr/include/libxml2 -I/usr/include/libgnome-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/orbit-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.0 -I/usr/include/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include    -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
リンク: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby2.1-2.1.2/debian/lib -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype   -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lgnomecanvas-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgdk_pixbuf-2.0 -lgnomevfs-2 -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib/x86_64-linux-gnu -lluajit-5.1 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.20/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions   -lruby-2.1 -lpthread -lgmp -ldl -lcrypt -lm    
```

**Comment by osyo-manga** [comment]
ありがとうございます。
`persistent_undo` が入ってないのかとも思いましたがそういうわけでもなさそうですね。
手元でも再現したパッチ（7.4.560）で試してみたのですがやはり再現はしませんでした。
こうなってくるとそちらでちょっと原因を調べてもらうしかなさそうな気がします。
とりあえず、実行、もしくはキャンセル時に[ここ](https://github.com/osyo-manga/vim-over/blob/master/autoload/over/command_line/substitute.vim#L50) が問題なく呼ばれている確認してもらえるとよいかと思います。

**Comment by aiya000** [comment]
こちらが実行した時のものです。
![vim-over_issuea](https://cloud.githubusercontent.com/assets/4897842/7003771/0df97278-dc9b-11e4-8c02-77322f4027b9.gif)

こちらが<Esc>でキャンセルした時のものです。
一応<C-c>もしてみましたが<Esc>と結果が同じでした。
![vim-over_issueb](https://cloud.githubusercontent.com/assets/4897842/7003776/24b739fa-dc9b-11e4-9297-50dca3d4d681.gif)

**Comment by osyo-manga** [comment]
ありがとうございます。
終了処理はちゃんと行われているみたいですね。
この[あたりの変数](https://github.com/osyo-manga/vim-over/blob/master/autoload/over/command_line/substitute.vim#L69)の内容も確認してもらえるとよいと思います。
もしかしたら `:wundo`、`:rundo` が正しく動作していないのかも知れません。

**Comment by aiya000** [comment]
こちらこそありがとうございますっ！

1度目の結果表示が実行した場合で、
2度目の結果表示がキャンセルした場合のものです。
![vim-over-issue-c](https://cloud.githubusercontent.com/assets/4897842/7003995/5164b05a-dc9f-11e4-9f9b-d7aecb117059.gif)

**Comment by osyo-manga** [comment]
うーん、問題なさそうな感じですねぇ。
これなんですが正しく動作していた時のバージョンとかってわかりますかね。

**Comment by aiya000** [comment]
すみませんわかりません…。
( 過去に正しく動作していたかもわかりません )

**Comment by osyo-manga** [comment]
ﾌｰﾑ
これって逆に正しく動作するケースはあるのでしょうか（e.g. `%s/foo/hoge/`

**Comment by aiya000** [comment]
正しく動作しますねー…。
![vim-over-act](https://cloud.githubusercontent.com/assets/4897842/7044350/85251580-de2d-11e4-82eb-fd6b0196d2ab.gif)

**Comment by osyo-manga** [comment]
ちょっと手を入れてみました。
更新して試してもらえないでしょうか。
あと実行後に `:mes` で何か出力されてないか確認してもらえると助かります。

**Comment by aiya000** [comment]
こうなってしまいました…。
![vim-over-foo-foo](https://cloud.githubusercontent.com/assets/4897842/7045460/3b298a40-de39-11e4-939e-569632a5bc24.gif)

**Comment by osyo-manga** [comment]
あーすみません、修正しました。
ついでに `:OverCommandLine s/foo/Foo` ではなくて `:OverCommandLine` 起動後に `s/foo/Foo/` を入力して試してもらえないでしょうか。
あと gif の画面はもう少し小さくしてもらえると（ファイルサイズと見やすさ的に）助かります。

**Comment by aiya000** [comment]
あああ、すみませんっ！
失礼な大きさ(！)でした…。

**Comment by aiya000** [comment]
やってみました、以前と変わらない様子です…。
![vim-over-o-ba](https://cloud.githubusercontent.com/assets/4897842/7046591/e48ee78a-de41-11e4-93fe-284ba18f3dea.gif)

**Comment by osyo-manga** [comment]
うーん、わからない…

**Comment by aiya000** [comment]
これ、一応Windows Kaoriya GVimとUbuntu Vimの2つの環境で再現を確認しているので
あ、 vim -u の -uオプションってもしかして、ftpluginを無効化しませんっけ…もしかしてしない？

**Comment by aiya000** [comment]
あ、でも今回filetype関係ないかー…。

**Comment by aiya000** [comment]
僕以外の再現がないようなので、とりあえずのところ閉じさせてください。
ありがとうございますっ。

**Comment by osyo-manga** [comment]
了解です。
また何かわかったら報告してもらえると助かります。
