### ISSUE TITLE
Doesn't highlight substitues with Vim 7.4

### ISSUE THREAD

**Issue by natemara** [osyo-manga/vim-over#40]
I can't get vim-over to highlight my substitute command. This is the output of `:version`:

	VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 20 2014 16:09:22)
	Included patches: 1-273
	Modified by pkg-vim-maintainers@lists.alioth.debian.org
	Compiled by buildd@
	Huge version without GUI.  Features included (+) or not (-):
	+acl             -clipboard       +cursorshape     +extra_search    -hangul_input    +listcmds        +mouse_gpm       -mzscheme        -python3         +startuptime     +termresponse    +viminfo         -xsmp
	+arabic          +cmdline_compl   +dialog_con      +farsi           +iconv           +localmap        -mouse_jsbterm   +netbeans_intg   +quickfix        +statusline      +textobjects     +vreplace        -xterm_clipboard
	+autocmd         +cmdline_hist    +diff            +file_in_path    +insert_expand   -lua             +mouse_netterm   +path_extra      +reltime         -sun_workshop    +title           +wildignore      -xterm_save
	-balloon_eval    +cmdline_info    +digraphs        +find_in_path    +jumplist        +menu            +mouse_sgr       -perl            +rightleft       +syntax          -toolbar         +wildmenu        -xpm
	-browse          +comments        -dnd             +float           +keymap          +mksession       -mouse_sysmouse  +persistent_undo -ruby            +tag_binary      +user_commands   +windows
	++builtin_terms  +conceal         -ebcdic          +folding         +langmap         +modify_fname    +mouse_urxvt     +postscript      +scrollbind      +tag_old_static  +vertsplit       +writebackup
	+byte_offset     +cryptv          +emacs_tags      -footer          +libcall         +mouse           +mouse_xterm     +printer         +signs           -tag_any_white   +virtualedit     -X11
	+cindent         +cscope          +eval            +fork()          +linebreak       -mouseshape      +multi_byte      +profile         +smartindent     -tcl             +visual          -xfontset
	-clientserver    +cursorbind      +ex_extra        +gettext         +lispindent      +mouse_dec       +multi_lang      +python          -sniff           +terminfo        +visualextra     -xim
	   system vimrc file: "$VIM/vimrc"
	     user vimrc file: "$HOME/.vimrc"
	 2nd user vimrc file: "~/.vim/vimrc"
	      user exrc file: "$HOME/.exrc"
	  fall-back for $VIM: "/usr/share/vim"
	Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -exp ort-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions

And this is my vimrc

	call plug#begin('~/.vim/plugged')

	Plug 'osyo-manga/vim-over'

	call plug#end()

	let g:over_enable_auto_nohlsearch = 1
	let g:over_enable_cmd_window = 1

**Comment by osyo-manga** [comment]
Thanks for issues.
Please tell me steps to reproduce.

**Comment by natemara** [comment]
Using the vimrc in my first post when I use the `:s` or `:substitute` command, no highlight or replacement text is shown.

**Comment by osyo-manga** [comment]
Thanks.
Please use `:substitute` in command line window(`q:`) or `:OverCommandLine`.

**Comment by natemara** [comment]
Thanks.
