### ISSUE TITLE
Unknown Operator Error '\z

### ISSUE THREAD

**Issue by jwmann** [osyo-manga/vim-over#42]
Hi there,

I'm trying to use the `\zs` and `\ze` operators within my regular expression however I receive this error as soon as I type `\z`

Version: 3.0, 10f7f7c66d00377a30abb49f21190d51ce8d0eee

### How to reproduce:
1) Initiate OverCommandLine command `:OverCommandLine`
2) Start Regular Expression `s/` (This also happens for `%s/`)
3) Type `\z`

Full Error:
`vital-over(_over):function <SNR>154_substitute_preview..<SNR>154_matchadd, line 2 Vim(call):E867: (NFA) Unknown operator '\z`

![screen shot 2015-04-15 at 12 47 04 pm](https://cloud.githubusercontent.com/assets/436270/7164442/37a10bac-e36e-11e4-94a7-15f996e7ba72.PNG)

**Comment by osyo-manga** [comment]
Thanks for issues.
I fixed it. Please update plugin.

**Comment by jwmann** [comment]
This fixed the issue! Thank you! :+1:
