### ISSUE TITLE
OverCommandLineが正常に起動しない

### ISSUE THREAD

**Issue by kagerouttepaso** [osyo-manga/vim-over#44]
windows 7 64bit環境、kaoriya版 vim 7.4 2015-3-1ビルド版で、最新のvim-overをneobundle経由でインストールし使用したところ下記のエラーが発生し`OverCommandLine`が使用できません。
VimプラグインはNeobundleとvim-overのみを使用しています。

```
function <SNR>92__to_modulename の処理中にエラーが検出されました
行 1:
E877: (FNA regexp) Invalid character class: 118
E63: \_ の無効な使用方法です
function <SNR>56_import..<SNR>56__import..<SNR>56__build_module..<SNR>56_loadの処理中にエラーが検出されました
行 19:
E171: :endifがありません
function <SNR>56_import..<SNR>56__import..<SNR>56__build_moduleの処理中にエラーが検出されました:
行  18:
E171: :endifがありません

```

**Comment by osyo-manga** [comment]
ありがとうございます。
こちらでも確認するためにエラーが発生する最小構成の vimrc と再現手順（どんな入力をした時に再現するのか etc）を教えて頂けると助かります。

**Comment by kagerouttepaso** [comment]
対応ありがとうございます。
vimrcと呼び出しに使用したコマンドをお送りします。

vimrc
``` vim
"~/.vimrc
" runtimepathの検索
if isdirectory($HOME."/.vim")
  let $DOTVIM_DIR = $HOME."/.vim"
elseif isdirectory($HOME."/vimfiles")
  let $DOTVIM_DIR = $HOME."/vimfiles"
elseif isdirectory($HOME."/dotfiles/_vim")
  let $DOTVIM_DIR = $HOME."/dotfiles/_vim"
endif
set encoding=utf-8    " デフォルトエンコーディング
if has('vim_starting')
  set nocompatible  " Be iMproved
  set runtimepath+=$DOTVIM_DIR/bundle/neobundle.vim/
  set maxfuncdepth=1000
endif

call neobundle#begin(expand($DOTVIM_DIR.'/bundle'))
" Let NeoBundle manage NeoBundle
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'osyo-manga/vim-over'
if neobundle#tap('vim-over') "{{{
  call neobundle#config({
        \  'autoload': {
        \    'commands': ['OverCommandLine'],
        \  }
        \})
  " ssで置換開始
  vnoremap <silent>ss :OverCommandLine<CR>s///g<Left><Left><Left>
  nnoremap <silent>ss :OverCommandLine<CR>%s///g<Left><Left><Left>
  " swでカーソル以下の単語を置換
  nnoremap <silent>sS :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>
  " virtualモード中は選択した文章で置き換え
  vnoremap <silent>sS y:OverCommandLine<CR>%s!<C-r>=substitute(@0, '!', '\\!', 'g')<CR>!!gI<Left><Left><Left>
  function! neobundle#hooks.on_source(bundle)
    " <C-l> を <C-f> に
    " <C-h> を <C-b> に割り当てる
    let g:over_command_line_key_mappings = {
          \  "\<C-l>": "\<C-f>",
          \  "\<C-h>": "\<C-b>",
          \}
  endfunction
  call neobundle#untap()
endif "}}}

call neobundle#end()
```

コマンド
`:OverCommandLine`

**Comment by osyo-manga** [comment]
ありがとうございます。
こちらでも調べてみます。

**Comment by kagerouttepaso** [comment]
補足です。
vimrcの最初にあるruntimepathの検索ですが、linux環境とwindows環境向けでbundleのフォルダを変更しています。
windows環境では`${home}/dotfiles`にhttps://github.com/kagerouttepaso/dotfiles をcloneしてきているため、`${home}/dotfiles/_vim/bundle`にvim-overがダウンロードされるようになっています。

**Comment by osyo-manga** [comment]
ありがとうございます。
修正してみたので更新して試してもらえないでしょうか。

**Comment by kagerouttepaso** [comment]
同じ環境でプラグインのみ更新した状態で試してみましたが、やはりエラーが発生しvim-overのコマンドラインが正常に起動しません。
エラーメッセージの内容は変化しているようです。エラーをお送りします。

```
function <SNR>59_import..<SNR>59__import..<SNR>59__build_module..<SNR>59_load..<SNR>59__import..<SNR>59__build_module..<SNR>59_expand_modules の処理中にエラーが検出されました:
行   14:
E605: 例外が捕捉されませんでした: vital: Module Unlocker.Holder.Buffer\Text is not found
function <SNR>59_import..<SNR>59__import..<SNR>59__build_module..<SNR>59_load..<SNR>59__import..<SNR>59__build_module の処理中にエラーが検出されました:
行   15:
E171: :endif がありません
function <SNR>59_import..<SNR>59__import..<SNR>59__build_module..<SNR>59_load の処理中にエラーが検出されました:
行   19:
E171: :endif がありません
function <SNR>59_import..<SNR>59__import..<SNR>59__build_module の処理中にエラーが検出されました:
行   18:
E171: :endif がありません
```

**Comment by osyo-manga** [comment]
すみません、修正したんですがコメントするのを忘れていました…。
最新版で試してもらえないでしょうか。

**Comment by kagerouttepaso** [comment]
最新版で確認をしたのですが、`:OverCommandLine`を呼び出したところでGvimが異常終了してしまいました。
エラーの詳細などは取得できませんでした。一応エラーのウィンドウをキャプチャしたものをお送りします。

![image](https://cloud.githubusercontent.com/assets/4670521/7507534/e321722a-f4ab-11e4-9d0b-3528128ba086.png)

**Comment by osyo-manga** [comment]
oh...
最近いろいろと修正したのでもしかしたら最初とは別のものが原因かも知れません。
一度 6fa49f6ad9eb63078f8fddeb0644e9bcd781817d のバージョンで試してもらえないでしょうか。

**Comment by osyo-manga** [comment]
あと上の vimrc だと neobundle.vim 経由で実行しているようですが、原因を切り分けるために 1度 neobundle.vim 経由でないやり方（直接 runtimepath へ追加する）で試してもらえると助かります。

**Comment by kagerouttepaso** [comment]
vimrc上の `set maxfuncdepth=1000` をコメントアウトしたところ、vim-overを直接ダウンロードした場合、neobundle.vimを使用してインストールした場合の両方で正常に動作することが確認できました。:)
一応これで問題は解決出来ましたが、原因究明の参考になりますかね

**Comment by osyo-manga** [comment]
ありがとうございます。
現状  `set maxfuncdepth=1000` を設定したらエラーになるという状況ですかね。

**Comment by osyo-manga** [comment]
再現した時の最小構成の vimrc などがあれば教えてもらえると助かります。

**Comment by kagerouttepaso** [comment]
vim-overをpluginsフォルダにcloneした状態で、vimrcに`set maxfuncdepth=1000`だけ記入したところ再現しました。

**Comment by osyo-manga** [comment]
ありがとうございます。
うーん、こちらの環境で試してみたけど特に問題はありませんでした。
`'maxfuncdepth'` の help によると

```
しかしこうするとメモリを余計に消費するので、メモリを使い果たしたときに落ち
る危険がある。|:function| も参照。
```

とあるので、もしかしたら over.vim ではなくて Vim 側（もしくはマシンの都合）の可能性もありますね。
ちなみに `maxfuncdepth` に設定できる値は `200` が最高だったりします。
see: https://github.com/vim-jp/issues/issues/270

**Comment by TPIPLAB** [comment]
maxfuncdepthを190にセットすると、上記の問題が発生しなくなりました。根本原因の究明にはもしかしたら意味があるかもしれません。

対応ありがとうございました。

**Comment by osyo-manga** [comment]
> maxfuncdepthを190にセットすると、上記の問題が発生しなくなりました。根本原因の究明にはもしかしたら意味があるかもしれません。

なるほど、ありがとうございます。
