### ISSUE TITLE
:OverCommandLine<CR> will throw exception

### ISSUE THREAD

**Issue by timfeirg** [osyo-manga/vim-over#45]
i'm on commit 46a3e99086be272e293731e76cd63cc6797ce1ef, and when I use :OverCommandLine, I'll get this error:

```
Error detected while processing function <SNR>133_import..<SNR>133__import:
line   12:
E605: Exception not caught: vital: module not found: Coaster.Highlight
Press ENTER or type command to continue
```

which obviously indicates a missing module in `autoload/over/command_line.vim`, line 13

let me guess, you forgot to `git add autoload/vital/_over/Coaster/Highlight.vim` or something?

**Comment by alexlafroscia** [comment]
:+1: I got the same error just now

**Comment by osyo-manga** [comment]
oooops, I fixed it.
Thanks for issues :))
