### ISSUE TITLE
Does it work in command editing mode?

### ISSUE THREAD

**Issue by kuator** [osyo-manga/vim-over#67]
Can I use it with `q:, q/, q?`
The gif in readme shows how substitute matches get highlighted.
But nothing gets highlighted in my case. :(
Steps to reproduce:

```
mkdir -p /tmp/issue && cd /tmp/issue/
git clone https://github.com/osyo-manga/vim-over

```
minimal.init
```

set runtimepath^=/tmp/issue/vim-over
filetype plugin on
set hlsearch
set incsearch

```
`nvim -u minimal.init sometext
`

**Comment by osyo-manga** [comment]
Thanks for issues.
I fixed https://github.com/osyo-manga/vim-over/commit/04a8e4b16795ef6c511be16bac4b2dd2b93255bf.

**Comment by kuator** [comment]
Thanks :)
